<map id="pymongo.database.Database.previous_error" name="pymongo.database.Database.previous_error">
<area shape="rect" id="node2" href="$classpymongo_1_1database_1_1_database.html#aad65a7eb2be557435c76fdedb277d180" title="pymongo.database.Database.command" alt="" coords="296,46,548,73"/>
<area shape="rect" id="node3" href="$classpymongo_1_1collection_1_1_collection.html#ad1d0fc1723fd58b098ebdaba5dfcab29" title="pymongo.collection.Collection.\l_command" alt="" coords="596,5,795,47"/>
<area shape="rect" id="node4" href="$classpymongo_1_1database_1_1_database.html#a65a133547fd9b3fd4f2ebf64b5082def" title="pymongo.database.Database.\l_command" alt="" coords="598,71,793,112"/>
</map>
