<map id="pymongo.errors.NetworkTimeout" name="pymongo.errors.NetworkTimeout">
<area shape="rect" id="node2" href="$classpymongo_1_1errors_1_1_auto_reconnect.html" title="pymongo.errors.AutoReconnect" alt="" coords="7,244,213,271"/>
<area shape="rect" id="node3" href="$classpymongo_1_1errors_1_1_connection_failure.html" title="pymongo.errors.Connection\lFailure" alt="" coords="19,155,201,196"/>
<area shape="rect" id="node4" href="$classpymongo_1_1errors_1_1_py_mongo_error.html" title="pymongo.errors.PyMongoError" alt="" coords="11,80,209,107"/>
</map>
